[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 10
y = 10

[font]
size = 14

  [font.normal]
  family = "Hack"
  style = "Regular"

  [font.bold]
  family = "Hack"
  style = "Bold"

  [font.italic]
  family = "Hack"
  style = "Italic"

  [font.bold_italic]
  family = "Hack"
  style = "Bold Italic"

[selection]
save_to_clipboard = true
